services:
  - type: web
    name: bot-web-app
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y portaudio19-dev 
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python Bot_web.py


