services:
  - type: web
    name: bot-web-app
    env: python
    buildCommand: |
      pip install --upgrade pip
      apt-get update
      apt-get install libportaudio2
      apt-get install -y portaudio19-dev 
      
      pip install -r requirements.txt
    startCommand: flet Bot_web.py


